---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
data:
  password: WU9VUl9QQVNTV09SRA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb14
  labels:
    app: mariadb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: mariadb:latest
          name: mariadb14
          command: ["bin/sh"]
          args: ["-c", while true; do echo "Pod -1 --- `date`"  >> /var/lib/mysql/rc-data.txt; sleep 1; done]
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: password
          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim: 
            claimName: pvc-ifds-14
