---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-chap-test-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: sc-provisionedvol-140
