apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: ci-snapclass
driver: csi.hpe.com
deletionPolicy: Delete
parameters:
  description: "Snapshot create by the HPE CSI Driver"
  csi.storage.k8s.io/snapshotter-secret-name: ci-hpe3parprimera-secret-snap
  csi.storage.k8s.io/snapshotter-secret-namespace: kube-system
