apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clone-of-ci-pvc-clonebase
spec:
  storageClassName: ci-3par-sc-clone
  dataSource:
    name: ci-pvc-clonebase
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

