---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-vg
  #namespace: namespace2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: sc-vg

