---
apiVersion: v1
kind: Pod
metadata:
  name: pod-4b3674cb
spec:
  containers:
  - name: minio
    image: minio/minio:latest
    imagePullPolicy: IfNotPresent
    args:
    - server
    - /export
    command: ["bin/sh"]
    args: ["-c", "while true; do date >> /export/mynewdata.txt; sleep 1; done"]
    env:
    - name: MINIO_ACCESS_KEY
      value: minio
    - name: MINIO_SECRET_KEY
      value: doryspeakswhale
    ports:
    - containerPort: 9000
    volumeMounts:
    - name: export
      mountPath: /export
  #nodeName: cssosbe01-196115.in.rdlabs.hpecorp.net
  volumes:
    - name: export
      persistentVolumeClaim:
        claimName: pvc-44288d99