---
apiVersion: v1
kind: Secret
metadata:
  name: ci-hpe3parprimera-secret-md-cpg1-dom-no
  namespace: kube-system
stringData:
  serviceName: primera3par-csp-svc
  servicePort: "8080"
  backend: 15.213.71.140
  username: 3paradm
data:
  # echo -n "3pardata" | base64
  password: M3BhcmRhdGE=
--- 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ci-sc-volume-md-cpg1-dom-no
provisioner: csi.hpe.com
parameters:
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: ci-hpe3parprimera-secret-md-cpg1-dom-no
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-publish-secret-name: ci-hpe3parprimera-secret-md-cpg1-dom-no
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: ci-hpe3parprimera-secret-md-cpg1-dom-no
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: ci-hpe3parprimera-secret-md-cpg1-dom-no
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  # Uncomment for k8s 1.14 for resize support
  #csi.storage.k8s.io/resizer-secret-name: nimble-secret
  #csi.storage.k8s.io/resizer-secret-namespace: kube-system
  # Uncomment for k8s 1.15 for resize support
  #csi.storage.k8s.io/controller-expand-secret-name: nimble-secret
  #csi.storage.k8s.io/controller-expand-secret-namespace: kube-
  cpg: "CI_CPG"
  provisioning_type: "tpvv"
  accessProtocol: "iscsi"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ci-pvc-volume-md-cpg1-dom-no
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 19Gi
  storageClassName: ci-sc-volume-md-cpg1-dom-no


---
apiVersion: v1
kind: Pod
metadata:
  name: ci-pod-volume-md-cpg1-dom-no
spec:
  containers:
  - name: minio
    image: minio/minio:latest
    args:
    - server
    - /export
    env:
    - name: MINIO_ACCESS_KEY
      value: minio
    - name: MINIO_SECRET_KEY
      value: doryspeakswhale
    ports:
    - containerPort: 9000
    volumeMounts:
    - name: export
      mountPath: /export
  nodeName: cssosbe01-196114.in.rdlabs.hpecorp.net
  volumes:
    - name: export
      persistentVolumeClaim:
        claimName: ci-pvc-volume-md-cpg1-dom-no


