---
kind: auto_data
vol_name: "ci-thin-absent-comp-impvol"
cpg: "CI_CPG"
provisioning_type: "tpvv"
---
apiVersion: v1
kind: Secret
metadata:
  name: ci-thin-absent-comp-impvol-secret
  namespace: kube-system
stringData:
  serviceName: primera3par-csp-svc
  servicePort: "8080"
  backend: 15.212.195.246
  username: 3paradm
data:
  # echo -n "3pardata" | base64
  password: M3BhcmRhdGE=
--- 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ci-thin-absent-comp-impvol-sc
provisioner: csi.hpe.com
parameters:
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: ci-thin-absent-comp-impvol-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-publish-secret-name: ci-thin-absent-comp-impvol-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: ci-thin-absent-comp-impvol-secret
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: ci-thin-absent-comp-impvol-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  # Uncomment for k8s 1.14 for resize support
  #csi.storage.k8s.io/resizer-secret-name: nimble-secret
  #csi.storage.k8s.io/resizer-secret-namespace: kube-system
  # Uncomment for k8s 1.15 for resize support
  #csi.storage.k8s.io/controller-expand-secret-name: nimble-secret
  #csi.storage.k8s.io/controller-expand-secret-namespace: kube-
  importVol: "ci-thin-absent-comp-impvol"
  accessProtocol: "iscsi"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ci-thin-absent-comp-impvol-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ci-thin-absent-comp-impvol-sc


---
apiVersion: v1
kind: Pod
metadata:
  name: ci-thin-absent-comp-impvol-pod
spec:
  containers:
  - name: minio
    image: minio/minio:latest
    args:
    - server
    - /export
    env:
    - name: MINIO_ACCESS_KEY
      value: minio
    - name: MINIO_SECRET_KEY
      value: doryspeakswhale
    ports:
    - containerPort: 9000
    volumeMounts:
    - name: export
      mountPath: /export
  volumes:
    - name: export
      persistentVolumeClaim:
        claimName: ci-thin-absent-comp-impvol-pvc


