---
kind: auto_data
vol_name: "snapshot-snap-of-base-impvol"
cpg: "CI_CPG"
snapCPG: "CI_CPG"
provisioning_type: "tpvv"
comment: "Snapshot starts with string snapshot-"
--- 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ci-name-start-snapshot-sc
provisioner: csi.hpe.com
parameters:
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: ci-primera3par-csp-secret
  csi.storage.k8s.io/provisioner-secret-namespace: hpe-storage
  csi.storage.k8s.io/controller-publish-secret-name: ci-primera3par-csp-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: hpe-storage
  csi.storage.k8s.io/node-stage-secret-name: ci-primera3par-csp-secret
  csi.storage.k8s.io/node-stage-secret-namespace: hpe-storage
  csi.storage.k8s.io/node-publish-secret-name: ci-primera3par-csp-secret
  csi.storage.k8s.io/node-publish-secret-namespace: hpe-storage
  # Uncomment for k8s 1.14 for resize support
  #csi.storage.k8s.io/resizer-secret-name: nimble-secret
  #csi.storage.k8s.io/resizer-secret-namespace: hpe-storage
  # Uncomment for k8s 1.15 for resize support
  #csi.storage.k8s.io/controller-expand-secret-name: nimble-secret
  #csi.storage.k8s.io/controller-expand-secret-namespace: kube-
  importVol: "ci-name-start-snapshot-impvol"
  accessProtocol: "iscsi"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ci-name-start-snapshot-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ci-name-start-snapshot-sc


---
apiVersion: v1
kind: Pod
metadata:
  name: ci-name-start-snapshot-pod
spec:
  containers:
  - name: minio
    image: minio/minio:latest
    imagePullPolicy: IfNotPresent
    args:
    - server
    - /export
    env:
    - name: MINIO_ACCESS_KEY
      value: minio
    - name: MINIO_SECRET_KEY
      value: doryspeakswhale
    ports:
    - containerPort: 9000
    volumeMounts:
    - name: export
      mountPath: /export
  volumes:
    - name: export
      persistentVolumeClaim:
        claimName: ci-name-start-snapshot-pvc


