apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: ci-snapclass
  namespace: hpe-storage
driver: csi.hpe.com
deletionPolicy: Delete
parameters:
  description: "Snapshot create by the HPE CSI Driver"
  csi.storage.k8s.io/snapshotter-secret-name: ci-primera3par-csp-secret
  csi.storage.k8s.io/snapshotter-secret-namespace: hpe-storage
