apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clone-of-ci-3par-csp-rep-pvc
spec:
  storageClassName: ci-3par-sc-rep
  dataSource:
    name: ci-3par-csp-rep-pvc
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi