kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ci-3par-csp-rep-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: ci-3par-sc-rep
