kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ci-3par-csp-rep-pvc-exp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ci-3par-sc-rep-exp
