---
apiVersion: v1
kind: Secret
metadata:
  name: hpe3parprimera-svc-secret
  namespace: hpe-storage
stringData:
  serviceName: primera3par-csp-svc
  servicePort: "8080"
  backend: 15.213.66.42
  username: 3paradm
data:
  # echo -n "3pardata" | base64
  password: M3BhcmRhdGE=


---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alletra-sc
provisioner: csi.hpe.com
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: hpe3parprimera-svc-secret
  csi.storage.k8s.io/provisioner-secret-namespace: hpe-storage
  csi.storage.k8s.io/controller-publish-secret-name: hpe3parprimera-svc-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: hpe-storage
  csi.storage.k8s.io/node-stage-secret-name: hpe3parprimera-svc-secret
  csi.storage.k8s.io/node-stage-secret-namespace: hpe-storage
  csi.storage.k8s.io/node-publish-secret-name: hpe3parprimera-svc-secret
  csi.storage.k8s.io/node-publish-secret-namespace: hpe-storage
  # Uncomment for k8s 1.14 for resize support
  #csi.storage.k8s.io/resizer-secret-name: nimble-secret
  #csi.storage.k8s.io/resizer-secret-namespace: kube-system
  # Uncomment for k8s 1.15 for resize support
  csi.storage.k8s.io/controller-expand-secret-name: hpe3parprimera-svc-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
  cpg: "CI_CPG"
  provisioning_type: "tpvv"
  accessProtocol: "iscsi"
  allowMutations: cpg,snapCpg,description,provisioningType,compression



---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alletra-pvc
  namespace: hpe-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 19Gi
  storageClassName: alletra-sc



---
kind: Pod
apiVersion: v1
metadata:
  name: alletra-pod
  namespace: hpe-storage
spec:
  containers:
  - name: minio
    image: minio/minio:latest
    imagePullPolicy: IfNotPresent
    args:
    - server
    - /export
    env:
    - name: MINIO_ACCESS_KEY
      value: minio
    - name: MINIO_SECRET_KEY
      value: doryspeakswhale
    ports:
    - containerPort: 9000
    volumeMounts:
    - name: export
      mountPath: /export
  volumes:
    - name: export
      persistentVolumeClaim:
        claimName: alletra-pvc


