---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-2
  namespace: hpe-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 19Gi
  storageClassName: 3par-sc2
