# Default values for hpe-csi-storage. 
 # This is a YAML-formatted file. 
 # Declare variables to be passed into your templates. 
  
 # image pull policy for all images in csi deployment 
 imagePullPolicy: 'IfNotPresent' 
  
 # flavor 
 flavor: kubernetes 
  
 # log level for all csi driver components 
 logLevel: trace
  
 ## For controlling automatic iscsi/multipath package installation (default: false) 
 disableNodeConformance: false 
  
 # values for CHAP Authentication 
 iscsi: 
   chapUser: "leena" 
   chapPassword: "LeenaJohn@123" 

