---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-importvol
spec:
    capacity:
      storage: 35Gi
    accessModes:
    - ReadWriteOnce
    flexVolume:
      driver: hpe.com/hpe
      options:
        name: VolFromArray
        importVol: ForAutoDocVol
        backend: 3par1
        
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-importvol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi
      
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-importvol
spec:
  containers:
  - name: minio
    image: minio/minio:latest
    args:
    - server
    - /export
    env:
    - name: MINIO_ACCESS_KEY
      value: minio
    - name: MINIO_SECRET_KEY
      value: doryspeakswhale
    ports:
    - containerPort: 9000
    volumeMounts:
    - name: export
      mountPath: /export
  volumes:
    - name: export
      persistentVolumeClaim:
        claimName: pvc-importvol
