--- 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ci-sc-volume-md-cpg3-dom-x
provisioner: csi.hpe.com
parameters:
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: ci-primera3par-csp-secret
  csi.storage.k8s.io/provisioner-secret-namespace: hpe-storage
  csi.storage.k8s.io/controller-publish-secret-name: ci-primera3par-csp-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: hpe-storage
  csi.storage.k8s.io/node-stage-secret-name: ci-primera3par-csp-secret
  csi.storage.k8s.io/node-stage-secret-namespace: hpe-storage
  csi.storage.k8s.io/node-publish-secret-name: ci-primera3par-csp-secret
  csi.storage.k8s.io/node-publish-secret-namespace: hpe-storage
  # Uncomment for k8s 1.14 for resize support
  #csi.storage.k8s.io/resizer-secret-name: nimble-secret
  #csi.storage.k8s.io/resizer-secret-namespace: hpe-storage
  # Uncomment for k8s 1.15 for resize support
  #csi.storage.k8s.io/controller-expand-secret-name: nimble-secret
  #csi.storage.k8s.io/controller-expand-secret-namespace: kube-
  cpg: "k8s_auto_test"
  provisioning_type: "tpvv"
  accessProtocol: "iscsi"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ci-pvc-volume-md-cpg3-dom-x
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 19Gi
  storageClassName: ci-sc-volume-md-cpg3-dom-x


---
apiVersion: v1
kind: Pod
metadata:
  name: ci-pod-volume-md-cpg3-dom-x
spec:
  containers:
  - name: minio
    image: minio/minio:latest
    args:
    - server
    - /export
    env:
    - name: MINIO_ACCESS_KEY
      value: minio
    - name: MINIO_SECRET_KEY
      value: doryspeakswhale
    ports:
    - containerPort: 9000
    volumeMounts:
    - name: export
      mountPath: /export
  nodeName: node-1
  volumes:
    - name: export
      persistentVolumeClaim:
        claimName: ci-pvc-volume-md-cpg3-dom-x


