---
apiVersion: v1
kind: Secret
metadata:
  name: ci-primera3par-csp-secret
  namespace: hpe-storage
stringData:
  serviceName: primera3par-csp-svc
  servicePort: "8080"
  backend: 15.213.71.140
  username: 3paradm
data:
  # echo -n "3pardata" | base64
  password: M3BhcmRhdGE=
