apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-pv
  namespace: hpe-storage
  labels:
    app: nginx-service-pv
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-service-pv
