---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: ci-pvc-snapshot
  namespace: hpe-storage
spec:
  volumeSnapshotClassName: ci-snapclass
  source:
    persistentVolumeClaimName: ci-pvc-snap-source
