--- 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ci-sc-volume-vol-exp
provisioner: csi.hpe.com
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: ci-primera3par-csp-secret
  csi.storage.k8s.io/provisioner-secret-namespace: hpe-storage
  csi.storage.k8s.io/controller-publish-secret-name: ci-primera3par-csp-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: hpe-storage
  csi.storage.k8s.io/node-stage-secret-name: ci-primera3par-csp-secret
  csi.storage.k8s.io/node-stage-secret-namespace: hpe-storage
  csi.storage.k8s.io/node-publish-secret-name: ci-primera3par-csp-secret
  csi.storage.k8s.io/node-publish-secret-namespace: hpe-storage
  # Uncomment for k8s 1.14 for resize support
  #csi.storage.k8s.io/resizer-secret-name: nimble-secret
  #csi.storage.k8s.io/resizer-secret-namespace: hpe-storage
  # Uncomment for k8s 1.15 for resize support
  csi.storage.k8s.io/controller-expand-secret-name: ci-primera3par-csp-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: hpe-storage
  cpg: "CI_CPG"
  provisioning_type: "tpvv"
  accessProtocol: "iscsi"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ci-pvc-volume-vol-exp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ci-sc-volume-vol-exp


