apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: ci-snapclass-level2-imp-vol
driver: csi.hpe.com
deletionPolicy: Delete
parameters:
  description: "Snapshot class to test snapshot importVol"
  csi.storage.k8s.io/snapshotter-secret-name: ci-base-for-snap-secret
  csi.storage.k8s.io/snapshotter-secret-namespace: kube-system
  importVol : "ci-snap-of-snap-impvol"
